/*
 * dsp_vectors.h - known-answer test data for the isolated benchmark.
 *
 * The data itself is in dsp_vectors.c, which is GENERATED by the host
 * reference generator together with dsp_coeffs.c. The two
 * files are one unit: the expected outputs were computed from the exact
 * coefficient values in dsp_coeffs.c, so regenerating one without the
 * other produces a test that fails for no real reason.
 *
 * Both arrays are stored as bit patterns rather than float literals. The
 * point of a known-answer test is to compare the exact numbers the
 * generator computed; routing them through the target compiler's decimal
 * parser first would put a second variable inside the comparison.
 *
 * The expected output is the DOUBLE-precision evaluation of the same DF2T
 * recursion, driven by the float32 coefficients and float32 inputs, then
 * rounded once to float32. It is therefore a reference the target is
 * measured against, not a second float32 implementation to be compared
 * with - the residual is float32 rounding inside the cascade and nothing
 * else. Coefficient and input quantisation are common to both sides and
 * cannot hide in it.
 */
#ifndef DSP_VECTORS_H
#define DSP_VECTORS_H

#include <stdint.h>

#include "arm_math_types.h"

#define DSP_VECTORS_CHANNELS    8u
#define DSP_VECTORS_FRAMES      32u
#define DSP_VECTORS_STAGES      6u

extern const uint32_t dsp_vectors_input_bits[DSP_VECTORS_CHANNELS][DSP_VECTORS_FRAMES];
extern const uint32_t dsp_vectors_expected_bits[DSP_VECTORS_CHANNELS][DSP_VECTORS_FRAMES];

/*
 * Pass tolerance, absolute.
 *
 * gen_reference.py measures the worst-case float32 rounding error over this
 * block by re-running the recursion with a rounding step after every
 * operation: 8.96e-08. That model rounds twice where the Cortex-M33
 * vfma.f32 rounds once, so it over-estimates the target error.
 *
 * 1.0e-06 is about 11x that measurement and sits at roughly -120 dBFS. It
 * is loose enough that ordinary float32 arithmetic passes with margin, and
 * tight enough that the three fault injections in dsp_bench_self_test()
 * all fail - which is the property that makes the number meaningful, and
 * the property that is actually tested rather than asserted.
 */
#define DSP_VECTORS_TOLERANCE   1.0e-06f

/* ------------------------------------------------------------------ */
/* Long cascade: the 84-section allpass bank                           */
/* ------------------------------------------------------------------ */
/*
 * Same input block, same channel count, DSP_COEFFS_AP_STAGES sections.
 *
 * Warm-up is part of the definition, not an optimisation: 84 allpass
 * sections delay the signal past one 32-sample block, so from zero state the
 * first block's output is nearly silence. The expected block below is the
 * one after DSP_VECTORS_AP_WARMUP_BLOCKS blocks of the same input, state
 * carried across. The generator computes it exactly that way.
 */
#define DSP_VECTORS_AP_STAGES           84u
#define DSP_VECTORS_AP_WARMUP_BLOCKS    8u

extern const uint32_t dsp_vectors_ap_expected_bits[DSP_VECTORS_CHANNELS][DSP_VECTORS_FRAMES];

/*
 * Tolerance for the long cascade.
 *
 * The float32-per-operation model measures 1.317e-06 over 84 sections -
 * about 15x the 6-section figure, which is what accumulating rounding
 * through 14x more feedback paths costs. 1.0e-05 is roughly 8x that
 * measurement. As with the short vectors, the number is only meaningful
 * because the fault injections still fail against it.
 */
#define DSP_VECTORS_AP_TOLERANCE        1.0e-05f

/* ------------------------------------------------------------------ */
/* Tier 2: the DRC-equivalent DSP block                                */
/* ------------------------------------------------------------------ */
/*
 * Raw slot values on both sides: an 8-slot interleaved int32 receive frame
 * in, a 4-slot interleaved int32 transmit frame out, DSP_VECTORS_FRAMES
 * frames. Slots 2..7 of the input carry full-scale alternating values that
 * must never reach the output, so a wrong input stride fails loudly.
 *
 * Compared with an INTEGER tolerance, not for equality: the expected side is
 * the double-precision evaluation of the chain, one LSB of float32 rounding
 * inside the cascade can move the truncated integer, and the 24-bit mask
 * leaves 8 bits below that. The tolerance is expressed in whole 32-bit slot
 * units - 256 is one LSB of the 24-bit field.
 */
#define DSP_VECTORS_T2_IN_SLOTS     8u
#define DSP_VECTORS_T2_OUT_SLOTS    4u
#define DSP_VECTORS_T2_TOLERANCE    (4 * 256)   /* 4 LSB of the 24-bit field */

extern const int32_t dsp_vectors_t2_rx[DSP_VECTORS_FRAMES * DSP_VECTORS_T2_IN_SLOTS];
extern const int32_t dsp_vectors_t2_tx[DSP_VECTORS_FRAMES * DSP_VECTORS_T2_OUT_SLOTS];

#endif /* DSP_VECTORS_H */
