/*
 * dsp_coeffs.h - the biquad cascade used by the isolated benchmark.
 *
 * One coefficient set, shared by every channel. That is deliberate and it
 * matches how a multichannel EQ is actually built: the *state* is per
 * channel, the coefficients are not. Sharing them also keeps the ROM cost
 * of a 16-channel variant flat.
 *
 * The values live in dsp_coeffs.c, which is GENERATED by the host reference
 * generator. Do not edit them by hand: the known
 * answer vectors in dsp_vectors.c were computed from exactly these numbers
 * and the two files must be regenerated together.
 */
#ifndef DSP_COEFFS_H
#define DSP_COEFFS_H

#include <stdbool.h>
#include <stdint.h>

#include "arm_math_types.h"

/* 12th-order Butterworth low-pass = 6 second-order sections. */
#define DSP_COEFFS_BW12_LP_STAGES   6u

/* CMSIS DF2T layout: {b0, b1, b2, -a1, -a2} per stage. */
extern const float32_t dsp_coeffs_bw12_lp[DSP_COEFFS_BW12_LP_STAGES * 5u];

/*
 * The bit pattern every literal in dsp_coeffs_bw12_lp[] must parse to.
 *
 * This exists because the coefficients are written as decimal literals but
 * the known-answer vectors were computed from specific binary32 values. A
 * 9-significant-digit literal round-trips binary32 exactly on a conforming
 * compiler - but "conforming" is an assumption, and an assumption that is
 * cheap to check should be checked.
 */
extern const uint32_t dsp_coeffs_bw12_lp_bits[DSP_COEFFS_BW12_LP_STAGES * 5u];

/*
 * The long-cascade bank: 84 second-order ALLPASS sections.
 *
 * 84 is the Sonora Classic/DRC record this project's comparison reproduces,
 * and the stage sweep has to reach it. The Butterworth bank above cannot be
 * used for that - 84 low-pass sections attenuate the signal until it is
 * denormal, and the timing then measures denormal handling rather than the
 * kernel. Every allpass section has |H| = 1 at every frequency, so cascade
 * length changes the phase and nothing else: no decay, no growth, bounded
 * state, and five non-trivial coefficients with a real feedback path.
 *
 * It is an instrument for timing a cascade length, not a filter anyone
 * would ship. Do not read an audio meaning into its output.
 *
 * IMPORTANT: |H| = 1 says nothing about group delay, and 84 sections delay
 * the signal well past one 32-sample block. Run from zero state the first
 * block is nearly silent, so both the known-answer test and the timing runs
 * warm the state with DSP_VECTORS_AP_WARMUP_BLOCKS whole blocks first.
 */
#define DSP_COEFFS_AP_STAGES        84u

extern const float32_t dsp_coeffs_ap84[DSP_COEFFS_AP_STAGES * 5u];
extern const uint32_t dsp_coeffs_ap84_bits[DSP_COEFFS_AP_STAGES * 5u];

/* True when every coefficient in BOTH banks holds exactly the intended
 * binary32 value. `first_bad` is set to the index of the first mismatch when
 * it fails, and `bad_bank` to the bank name. */
bool dsp_coeffs_self_check(uint32_t *first_bad);
bool dsp_coeffs_self_check_all(uint32_t *first_bad, const char **bad_bank);

#endif /* DSP_COEFFS_H */
